### ISSUE TITLE
sig_profiler.py incorrect directory name for SBS_De_Novo_Solution/Signatures

### ISSUE THREAD

**Issue by esavage111** [catg-umag/bcell-lymphomas-mutational-signatures#3]
When running script on paper data, get following error that seems to be related to folder name in python script indicated above:

```
Traceback (most recent call last): [K
    File "/home/user/.nextflow/assets/CATG-UMAG/bcell-lymphomas-mutational-signatures/bin/sig_profiler.py", line 108, in <module> [K
      main() [K
    File "/home/user/.nextflow/assets/CATG-UMAG/bcell-lymphomas-mutational-signatures/bin/sig_profiler.py", line 34, in main [K
      x for x in listdir(base_dir) if re.match(r"SBS96_.*_Signatures.txt", x) [K
  FileNotFoundError: [Errno 2] No such file or directory: 'sigprofiler_out/SBS96/Suggested_Solution/SBS96_De_Novo_Solution/Signatures' [K
 [K
Work dir: [K
  /work/40/464fbeeb25e05f67e3327fe8aa52d8 [K
 [K
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line [K  [K  [39m [K
```

I have changed the directory name to correct name ("SBS_De-Novo_Solution/Signatures") in my local version of the sig_profiler.py script and am testing running the analysis on hpc node now.

**Comment by dialvarezs** [comment]
You're right, I missed that. Thank you!
